# Prototypes for spawning in Enclave urists
# Enlisted & Officers

- type: entity
  parent: MobHuman
  id: N14MobHumanEnclaveEnlisted
  name: Enclave Enlisted
  components:
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [EnclaveEnlistedGear]
    - type: NpcFactionMember
      factions:
      - Enclave

- type: entity
  parent: MobHuman
  id: N14MobHumanEnclaveNCO
  name: Enclave NCO
  components:
  - type: RandomHumanoidAppearance
    randomizeName: true
  - type: Loadout
    prototypes: [EnclaveNCOGear]
  - type: NpcFactionMember
    factions:
    - Enclave

- type: entity
  parent: MobHuman
  id: N14MobHumanEnclaveJuniorOfficer
  name: Enclave Junior Officer
  components:
  - type: RandomHumanoidAppearance
    randomizeName: true
  - type: Loadout
    prototypes: [EnclaveJuniorOfficerGear]
  - type: NpcFactionMember
    factions:
    - Enclave

- type: entity
  parent: MobHuman
  id: N14MobHumanEnclaveSeniorOfficer
  name: Enclave Senior Officer
  components:
  - type: RandomHumanoidAppearance
    randomizeName: true
  - type: Loadout
    prototypes: [EnclaveSeniorOfficerGear]
  - type: NpcFactionMember
    factions:
    - Enclave

# Commander & Reformer

- type: entity
  parent: MobHuman
  id: N14MobHumanEnclaveCommander
  name: Enclave Commander
  components:
  - type: RandomHumanoidAppearance
    randomizeName: true
  - type: Loadout
    prototypes: [EnclaveCommanderGear]
  - type: NpcFactionMember
    factions:
    - Enclave

- type: entity
  parent: MobHuman
  id: N14MobHumanEnclaveReformer
  name: Enclave Reformer
  components:
  - type: RandomHumanoidAppearance
    randomizeName: true
  - type: Loadout
    prototypes: [EnclaveCommanderGear]
  - type: NpcFactionMember
    factions:
    - Enclave

# Science Team

- type: entity
  parent: MobHuman
  id: N14MobHumanEnclaveJuniorScientist
  name: Enclave Junior Scientist
  components:
  - type: RandomHumanoidAppearance
    randomizeName: true
  - type: Loadout
    prototypes: [EnclaveJuniorScientistGear]
  - type: NpcFactionMember
    factions:
    - Enclave

- type: entity
  parent: MobHuman
  id: N14MobHumanEnclaveScientist
  name: Enclave Scientist
  components:
  - type: RandomHumanoidAppearance
    randomizeName: true
  - type: Loadout
    prototypes: [EnclaveScientistGear]
  - type: NpcFactionMember
    factions:
    - Enclave

- type: entity
  parent: MobHuman
  id: N14MobHumanEnclaveHeadScientist
  name: Enclave Head Scientist
  components:
  - type: RandomHumanoidAppearance
    randomizeName: true
  - type: Loadout
    prototypes: [EnclaveHeadScientistGear]
  - type: NpcFactionMember
    factions:
    - Enclave

# Super Mutant

- type: entity
  parent: N14MobSuperMutant
  id: N14MobSupermutantEnclave
  name: Enclave Supermutant
  components:
  - type: RandomHumanoidAppearance
    randomizeName: true
  - type: Loadout
    prototypes: [SuperMutantEnclaveGear]
  - type: NpcFactionMember
    factions:
    - Enclave
