using Content.Client.UserInterface.Controls;
using Content.Shared._Misfits.Vehicles.Vertibird;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.Vehicles.Vertibird;

[GenerateTypedNameReferences]
public sealed partial class VertibirdWindow : FancyWindow
{
    public event Action<int>? OnSeatSelected;

    public VertibirdWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetState(VertibirdSeatBoundUserInterfaceState state)
    {
        StatusLabel.Text = Loc.GetString("vertibird-window-status", ("state", state.FlightState.ToString()));
        SeatList.RemoveAllChildren();

        foreach (var seat in state.Seats)
        {
            SeatList.AddChild(BuildSeatRow(seat, state.FlightState));
        }
    }

    private Control BuildSeatRow(VertibirdSeatUiState seat, VertibirdFlightState flightState)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 6),
        };

        var label = new Label
        {
            Text = seat.Name,
            HorizontalExpand = true,
        };

        var occupant = new Label
        {
            Text = seat.OccupantName ?? Loc.GetString("vertibird-seat-empty"),
            MinWidth = 110,
        };

        var button = new Button
        {
            Text = seat.OccupantName == null
                ? Loc.GetString("vertibird-seat-board")
                : Loc.GetString("vertibird-seat-occupied"),
            Disabled = seat.OccupantName != null || flightState != VertibirdFlightState.Grounded,
            MinWidth = 84,
        };

        if (seat.RequiresPilotPerk)
            button.ToolTip = Loc.GetString("vertibird-seat-requires-perk");

        button.OnPressed += _ => OnSeatSelected?.Invoke(seat.Index);

        row.AddChild(label);
        row.AddChild(occupant);
        row.AddChild(button);
        return row;
    }
}
