// #Cythisiax Add - Market terminal GUI window
using Content.Shared._Misfits.Trade.Market;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.Trade.Market;

[GenerateTypedNameReferences]
public sealed partial class MarketWindow : DefaultWindow
{
    public event Action? OnClose;
    public event Action<MarketListMessage>? OnListRequest;
    public event Action<string, int>? OnBuyRequest;

    private readonly List<string> _currencyOptions = new() { "Bottlecaps", "NCRDollars", "Silver", "Gold", "Barter" };

    public MarketWindow()
    {
        RobustXamlLoader.Load(this);

        Title = "Wendover Free Market";
        SetSize = new(900, 650);

        // Wire tab buttons
        TabMarketBtn.OnPressed += _ => SwitchTab(0);
        TabMyListingsBtn.OnPressed += _ => SwitchTab(1);
        TabListNewBtn.OnPressed += _ => SwitchTab(2);
        TabActivityBtn.OnPressed += _ => SwitchTab(3);

        // Populate currency dropdown
        foreach (var cur in _currencyOptions)
        {
            ListCurrency.AddItem(cur);
            ListCurrency.SetItemMetadata(ListCurrency.ItemCount - 1, cur);
        }

        ListCurrency.OnItemSelected += args =>
        {
            ListCurrency.SelectId(args.Id);
            var isBarter = (string?) ListCurrency.SelectedMetadata == "Barter";
            BarterRow.Visible = isBarter;
            BarterQtyRow.Visible = isBarter;
            UpdateFeeLabel();
        };

        ListPrice.OnTextChanged += _ => UpdateFeeLabel();

        // List item submission
        ListSubmitBtn.OnPressed += _ => SubmitListing();
    }

    private void SwitchTab(int index)
    {
        TabMarketContent.Visible = index == 0;
        TabMyListingsContent.Visible = index == 1;
        TabListNewContent.Visible = index == 2;
        TabActivityContent.Visible = index == 3;

        TabMarketBtn.Disabled = index == 0;
        TabMyListingsBtn.Disabled = index == 1;
        TabListNewBtn.Disabled = index == 2;
        TabActivityBtn.Disabled = index == 3;
    }

    public void SetMarketName(string name)
    {
        Title = name;
    }

    public void UpdateBalances(int caps, int ncr, int silver, int gold)
    {
        CapsLabel.Text = $"Caps: {caps}";
        NcrLabel.Text = $"NCR: {ncr}";
        SilverLabel.Text = $"Silver: {silver}";
        GoldLabel.Text = $"Gold: {gold}";
    }

    public void UpdateListings(List<MarketListingData> listings)
    {
        MarketListContainer.RemoveAllChildren();

        if (listings.Count == 0)
        {
            MarketListContainer.AddChild(new Label { Text = "No active listings." });
            return;
        }

        foreach (var listing in listings)
        {
            var box = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 8 };
            var text = $"[{listing.Currency}] {listing.PrototypeName} x{listing.Quantity} — {listing.PricePerUnit}/ea — by {listing.SellerName}";
            box.AddChild(new Label { Text = text, HorizontalExpand = true });
            var buyBtn = new Button { Text = "Buy", MinWidth = 60 };
            var listingId = listing.ListingId;
            buyBtn.OnPressed += _ => OnBuyRequest?.Invoke(listingId, 1);
            box.AddChild(buyBtn);
            MarketListContainer.AddChild(box);
        }
    }

    public void UpdateMyListings(List<MarketListingData> listings)
    {
        MyListingsContainer.RemoveAllChildren();

        if (listings.Count == 0)
        {
            MyListingsContainer.AddChild(new Label { Text = "You have no active listings." });
            return;
        }

        foreach (var listing in listings)
        {
            var text = $"[{listing.Currency}] {listing.PrototypeName} x{listing.Quantity} — {listing.PricePerUnit}/ea — Expires: {listing.ExpiresAt:yyyy-MM-dd HH:mm}";
            MyListingsContainer.AddChild(new Label { Text = text });
        }
    }

    public void UpdateFeed(List<MarketFeedEntry> feed)
    {
        FeedContainer.RemoveAllChildren();

        if (feed.Count == 0)
        {
            FeedContainer.AddChild(new Label { Text = "No market activity yet." });
            return;
        }

        foreach (var entry in feed)
        {
            var timeStr = entry.Time.ToLocalTime().ToString("HH:mm");
            FeedContainer.AddChild(new Label { Text = $"[{timeStr}] {entry.Text}" });
        }
    }

    private void UpdateFeeLabel()
    {
        var currency = (string?) ListCurrency.SelectedMetadata;
        if (string.IsNullOrEmpty(currency))
            return;
        if (!int.TryParse(ListPrice.Text, out var price) || price <= 0)
        {
            ListFeeLabel.Text = "";
            return;
        }

        if (currency == "Barter")
        {
            ListFeeLabel.Text = "No fee (barter)";
            return;
        }

        var fee = price / 10; // 10% rounded down
        ListFeeLabel.Text = $"Fee: {fee} {currency}";
    }

    private void SubmitListing()
    {
        var protoId = ListProtoId.Text.Trim();
        if (string.IsNullOrEmpty(protoId))
            return;

        if (!int.TryParse(ListQuantity.Text, out var qty) || qty <= 0)
            qty = 1;

        if (!int.TryParse(ListStackCount.Text, out var stackCount))
            stackCount = 0;

        var currency = (string?) ListCurrency.SelectedMetadata;
        if (string.IsNullOrEmpty(currency))
            return;

        if (!int.TryParse(ListPrice.Text, out var price) || price <= 0)
            return;

        string? requestedItem = null;
        int requestedQty = 0;
        if (currency == "Barter")
        {
            requestedItem = ListRequestedItem.Text.Trim();
            if (!int.TryParse(ListRequestedQty.Text, out requestedQty) || requestedQty <= 0)
                return;
        }

        OnListRequest?.Invoke(new MarketListMessage(protoId, qty, stackCount, currency, price, requestedItem, requestedQty));
    }
}
