// #Cythisiax Add - Market terminal GUI window
using Content.Shared._Misfits.Trade.Market;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.Trade.Market;

[GenerateTypedNameReferences]
public sealed partial class MarketWindow : DefaultWindow
{
    public event Action? OnClose;
    public event Action<MarketListMessage>? OnListRequest;
    public event Action<string, int>? OnBuyRequest;

    private readonly List<string> _currencyOptions = new() { "Bottlecaps", "NCRDollars", "Silver", "Gold", "Barter" };
    private string? _selectedDepositSlot;

    public MarketWindow()
    {
        RobustXamlLoader.Load(this);

        Title = "Wendover Free Market";
        SetSize = new(900, 650);

        // Wire tab buttons
        TabMarketBtn.OnPressed += _ => SwitchTab(0);
        TabMyListingsBtn.OnPressed += _ => SwitchTab(1);
        TabListNewBtn.OnPressed += _ => SwitchTab(2);
        TabActivityBtn.OnPressed += _ => SwitchTab(3);

        // Populate currency dropdown
        foreach (var cur in _currencyOptions)
        {
            ListCurrency.AddItem(cur);
            ListCurrency.SetItemMetadata(ListCurrency.ItemCount - 1, cur);
        }

        ListCurrency.OnItemSelected += args =>
        {
            ListCurrency.SelectId(args.Id);
            var isBarter = (string?) ListCurrency.SelectedMetadata == "Barter";
            BarterPanel.Visible = isBarter;
            UpdateFeeLabel();
        };

        ListPrice.OnTextChanged += _ => UpdateFeeLabel();

        // Withdraw event is wired per-item in UpdateDepositedItems

        // List item submission
        ListSubmitBtn.OnPressed += _ => SubmitListing();
    }

    public void UpdateDepositedItems(List<MarketDepositEntry> items, Action<string>? onWithdraw)
    {
        DepositItemsContainer.RemoveAllChildren();

        if (items.Count == 0)
        {
            DepositItemsContainer.AddChild(new Label
            {
                Text = "No items deposited. Hold an item and click 'Deposit Held Item'.",
                StyleClasses = { "LabelSubText" },
                Margin = new Thickness(4),
            });
            return;
        }

        foreach (var entry in items)
        {
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 8 };
            var label = new Label
            {
                Text = $"{entry.ProtoName} x{entry.Quantity}" + (entry.StackCount > 0 ? $" ({entry.StackCount} stack)" : ""),
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center,
            };
            row.AddChild(label);

            var selectBtn = new Button { Text = "Select", MinWidth = 60 };
            var slot = entry.SlotKey;
            var protoId = entry.ProtoId;
            var stackCount = entry.StackCount;
            selectBtn.OnPressed += _ =>
            {
                _selectedDepositSlot = slot;
                ListProtoId.Text = protoId;
                ListStackCount.Text = stackCount > 0 ? stackCount.ToString() : "0";
            };
            row.AddChild(selectBtn);

            var withdrawBtn = new Button { Text = "Take", MinWidth = 50 };
            var wSlot = entry.SlotKey;
            withdrawBtn.OnPressed += _ => onWithdraw?.Invoke(wSlot);
            row.AddChild(withdrawBtn);

            DepositItemsContainer.AddChild(row);
        }
    }

    private void SwitchTab(int index)
    {
        TabMarketContent.Visible = index == 0;
        TabMyListingsContent.Visible = index == 1;
        TabListNewContent.Visible = index == 2;
        TabActivityContent.Visible = index == 3;

        TabMarketBtn.Disabled = index == 0;
        TabMyListingsBtn.Disabled = index == 1;
        TabListNewBtn.Disabled = index == 2;
        TabActivityBtn.Disabled = index == 3;
    }

    public void SetMarketName(string name) => Title = name;

    public void UpdateBalances(int caps, int ncr, int silver, int gold)
    {
        CapsLabel.Text = $"Caps: {caps}";
        NcrLabel.Text = $"NCR: {ncr}";
        SilverLabel.Text = $"Silver: {silver}";
        GoldLabel.Text = $"Gold: {gold}";
    }

    // ── EVE-like Item Overview tab ────────────────────────────────────────────

    public void UpdateItemSummaries(List<MarketItemSummary> summaries)
    {
        MarketItemsContainer.RemoveAllChildren();

        if (summaries.Count == 0)
        {
            MarketItemsContainer.AddChild(new Label
            {
                Text = "No items listed on the market.",
                StyleClasses = { "LabelSubText" },
                Margin = new Thickness(4),
            });
            return;
        }

        // Header row
        var header = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 8 };
        header.AddChild(new Label { Text = "Item", MinWidth = 200, StyleClasses = { "LabelHeading" } });
        header.AddChild(new Label { Text = "#", MinWidth = 40, StyleClasses = { "LabelHeading" } });
        header.AddChild(new Label { Text = "Low", MinWidth = 50, StyleClasses = { "LabelHeading" } });
        header.AddChild(new Label { Text = "High", MinWidth = 50, StyleClasses = { "LabelHeading" } });
        header.AddChild(new Label { Text = "Curr.", MinWidth = 60, StyleClasses = { "LabelHeading" } });
        MarketItemsContainer.AddChild(header);

        foreach (var s in summaries)
        {
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 8 };
            row.AddChild(new Label { Text = s.PrototypeName, MinWidth = 200 });
            row.AddChild(new Label { Text = s.ListingCount.ToString(), MinWidth = 40 });
            row.AddChild(new Label { Text = s.LowestPrice > 0 ? s.LowestPrice.ToString() : "—", MinWidth = 50 });
            row.AddChild(new Label { Text = s.HighestPrice > 0 ? s.HighestPrice.ToString() : "—", MinWidth = 50 });
            row.AddChild(new Label { Text = s.Currency, MinWidth = 60 });

            var expandBtn = new Button { Text = "View", MinWidth = 60 };
            expandBtn.OnPressed += _ => ShowItemListings(s.PrototypeId);
            row.AddChild(expandBtn);

            MarketItemsContainer.AddChild(row);
        }
    }

    private void ShowItemListings(string prototypeId)
    {
        // Open a popup or switch context — for now, just filter the "Market" view
        // (Full listing detail is Phase 5 graphs — this stub opens nothing)
    }

    public void UpdateListings(List<MarketListingData> listings)
    {
        // Listings are now shown via item summaries; individual listing entries shown on demand
    }

    public void UpdateMyListings(List<MarketListingData> listings)
    {
        MyListingsContainer.RemoveAllChildren();

        if (listings.Count == 0)
        {
            MyListingsContainer.AddChild(new Label
            {
                Text = "You have no active listings.",
                StyleClasses = { "LabelSubText" },
                Margin = new Thickness(4),
            });
            return;
        }

        foreach (var listing in listings)
        {
            var panel = new PanelContainer { StyleClasses = { "PanelDark" }, Margin = new Thickness(0, 2) };
            var box = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, Margin = new Thickness(6, 4) };
            box.AddChild(new Label
            {
                Text = $"{listing.PrototypeName} x{listing.Quantity} — {listing.PricePerUnit}/ea {listing.Currency}",
                StyleClasses = { "LabelHeading" },
            });
            box.AddChild(new Label
            {
                Text = $"Listed: {listing.ListedAt.ToLocalTime():yyyy-MM-dd HH:mm}  |  Expires: {listing.ExpiresAt.ToLocalTime():yyyy-MM-dd HH:mm}",
                StyleClasses = { "LabelSubText" },
            });
            panel.AddChild(box);
            MyListingsContainer.AddChild(panel);
        }
    }

    public void UpdateFeed(List<MarketFeedEntry> feed)
    {
        FeedContainer.RemoveAllChildren();

        if (feed.Count == 0)
        {
            FeedContainer.AddChild(new Label
            {
                Text = "No market activity yet.",
                StyleClasses = { "LabelSubText" },
                Margin = new Thickness(4),
            });
            return;
        }

        foreach (var entry in feed)
        {
            var timeStr = entry.Time.ToLocalTime().ToString("HH:mm");
            FeedContainer.AddChild(new Label
            {
                Text = $"[{timeStr}] {entry.Text}",
                StyleClasses = { "LabelSubText" },
            });
        }
    }

    private void UpdateFeeLabel()
    {
        var currency = (string?) ListCurrency.SelectedMetadata;
        if (string.IsNullOrEmpty(currency))
            return;
        if (!int.TryParse(ListPrice.Text, out var price) || price <= 0)
        {
            ListFeeLabel.Text = "";
            return;
        }

        if (currency == "Barter")
        {
            ListFeeLabel.Text = "No fee (barter)";
            return;
        }

        var fee = price / 10;
        ListFeeLabel.Text = $"Fee: {fee} {currency}";
    }

    private void SubmitListing()
    {
        var protoId = ListProtoId.Text.Trim();
        if (string.IsNullOrEmpty(protoId))
            return;

        if (!int.TryParse(ListQuantity.Text, out var qty) || qty <= 0)
            qty = 1;

        if (!int.TryParse(ListStackCount.Text, out var stackCount))
            stackCount = 0;

        var currency = (string?) ListCurrency.SelectedMetadata;
        if (string.IsNullOrEmpty(currency))
            return;

        if (!int.TryParse(ListPrice.Text, out var price) || price <= 0)
            return;

        string? requestedItem = null;
        int requestedQty = 0;
        if (currency == "Barter")
        {
            requestedItem = ListRequestedItem.Text.Trim();
            if (!int.TryParse(ListRequestedQty.Text, out requestedQty) || requestedQty <= 0)
                return;
        }

        OnListRequest?.Invoke(new MarketListMessage(protoId, qty, stackCount, currency, price, requestedItem, requestedQty));
    }
}
