// #Cythisiax Add - Wendover Free Market Exchange client window
using Content.Shared._Misfits.Trade.Market;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.Trade.Market;

[GenerateTypedNameReferences]
public sealed partial class MarketWindow : DefaultWindow
{
    public event Action<CreateOrderMessage>? OnListRequest;
    public event Action<string, int>? OnBuyRequest;
    public event Action<string>? OnClaim;
    public event Action<string>? OnCancel;
    public event Action<string>? OnProtoSearch;

    private string? _selectedProtoId;
    private string? _selectedProtoName;

    public MarketWindow()
    {
        RobustXamlLoader.Load(this);

        TabExchangeBtn.OnPressed += _ => SwitchTab(0);
        TabCreateBtn.OnPressed += _ => SwitchTab(1);
        TabMyOrdersBtn.OnPressed += _ => SwitchTab(2);
        TabActivityBtn.OnPressed += _ => SwitchTab(3);

        OrderTypeBtn.AddItem("Sell Order"); OrderTypeBtn.SetItemMetadata(0, false);
        OrderTypeBtn.AddItem("Buy Order"); OrderTypeBtn.SetItemMetadata(1, true);

        foreach (var c in new[] { "Bottlecaps", "NCRDollars", "Silver", "Gold", "Barter" })
        {
            OrderCurrencyBtn.AddItem(c);
            OrderCurrencyBtn.SetItemMetadata(OrderCurrencyBtn.ItemCount - 1, c);
        }
        OrderCurrencyBtn.OnItemSelected += _ => OrderCurrencyBtn.SelectId(OrderCurrencyBtn.SelectedId);

        OrderPrice.OnTextChanged += _ => UpdateFeeLabel();
        SubmitOrderBtn.OnPressed += _ => SubmitOrder();
        ProtoSearchBtn.OnPressed += _ => OnProtoSearch?.Invoke(ProtoSearch.Text.Trim());
    }

    private void SwitchTab(int i)
    {
        TabExchange.Visible = i == 0; TabExchangeBtn.Disabled = i == 0;
        TabCreate.Visible = i == 1; TabCreateBtn.Disabled = i == 1;
        TabMyOrders.Visible = i == 2; TabMyOrdersBtn.Disabled = i == 2;
        TabActivity.Visible = i == 3; TabActivityBtn.Disabled = i == 3;
    }

    public void UpdateBalances(int caps, int ncr, int silver, int gold)
    {
        CapsLabel.Text = $"Caps: {caps}";
        NcrLabel.Text = $"NCR: {ncr}";
        SilverLabel.Text = $"Silver: {silver}";
        GoldLabel.Text = $"Gold: {gold}";
    }

    public void UpdateItemSummaries(List<MarketItemSummary> summaries)
    {
        ItemDirectory.RemoveAllChildren();
        ItemDirectory.AddChild(new Label { Text = "Item Directory", StyleClasses = { "LabelHeading" }, Margin = new Thickness(0, 0, 0, 4) });

        var hdr = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 4 };
        hdr.AddChild(new Label { Text = "Item", MinWidth = 100, StyleClasses = { "LabelSubText" } });
        hdr.AddChild(new Label { Text = "Ask", MinWidth = 40, StyleClasses = { "LabelSubText" } });
        hdr.AddChild(new Label { Text = "Bid", MinWidth = 40, StyleClasses = { "LabelSubText" } });
        ItemDirectory.AddChild(hdr);

        foreach (var s in summaries)
        {
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 4 };
            row.AddChild(new Label { Text = s.PrototypeName, MinWidth = 100 });
            row.AddChild(new Label { Text = s.BestAsk > 0 ? s.BestAsk.ToString() : "-", MinWidth = 40 });
            row.AddChild(new Label { Text = s.BestBid > 0 ? s.BestBid.ToString() : "-", MinWidth = 40 });
            var btn = new Button { Text = "View", MinWidth = 50 };
            btn.OnPressed += _ => OnBuyRequest?.Invoke(s.PrototypeId, 0);
            row.AddChild(btn);
            ItemDirectory.AddChild(row);
        }
    }

    public void UpdateDepositedItems(List<MarketDepositEntry> items, Action<string>? onWithdraw)
    {
        DepositItemsContainer.RemoveAllChildren();
        if (items.Count == 0)
        {
            DepositItemsContainer.AddChild(new Label { Text = "No items in storage.", StyleClasses = { "LabelSubText" }, Margin = new Thickness(4) });
            return;
        }
        foreach (var e in items)
        {
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 8 };
            row.AddChild(new Label { Text = $"{e.ProtoName} x{e.Quantity}" + (e.StackCount > 0 ? $" ({e.StackCount})" : ""), HorizontalExpand = true, VerticalAlignment = VAlignment.Center });

            var listBtn = new Button { Text = "List", MinWidth = 50 };
            var protoId = e.ProtoId;
            var protoName = e.ProtoName;
            listBtn.OnPressed += _ =>
            {
                _selectedProtoId = protoId;
                _selectedProtoName = protoName;
                SelectedProtoLabel.Text = $"{protoName} ({protoId})";
            };
            row.AddChild(listBtn);

            var wBtn = new Button { Text = "Take", MinWidth = 50 };
            var s = e.SlotKey;
            wBtn.OnPressed += _ => onWithdraw?.Invoke(s);
            row.AddChild(wBtn);
            DepositItemsContainer.AddChild(row);
        }
    }

    public void UpdateMyOrders(List<MarketOrder> orders, List<MarketOrder> completed)
    {
        MyOrdersContainer.RemoveAllChildren();
        if (orders.Count == 0)
            MyOrdersContainer.AddChild(new Label { Text = "No active orders.", StyleClasses = { "LabelSubText" }, Margin = new Thickness(4) });
        foreach (var o in orders)
        {
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 8, Margin = new Thickness(0, 1) };
            row.AddChild(new Label { Text = $"{(o.IsBuyOrder ? "BUY" : "SELL")} {o.PrototypeName} x{o.Quantity} @ {o.Price}/ea {o.Currency} — {o.FulfilledQty}/{o.Quantity} filled", HorizontalExpand = true });
            var cb = new Button { Text = "Cancel", MinWidth = 60 };
            var oid = o.OrderId;
            cb.OnPressed += _ => OnCancel?.Invoke(oid);
            row.AddChild(cb);
            MyOrdersContainer.AddChild(row);
        }

        MyCompletedContainer.RemoveAllChildren();
        if (completed.Count == 0)
            MyCompletedContainer.AddChild(new Label { Text = "No completed orders.", StyleClasses = { "LabelSubText" }, Margin = new Thickness(4) });
        foreach (var o in completed)
        {
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 8, Margin = new Thickness(0, 1) };
            row.AddChild(new Label { Text = $"{(o.IsBuyOrder ? "BUY" : "SELL")} {o.PrototypeName} x{o.Quantity} @ {o.Price}/ea {o.Currency} — Fulfilled", HorizontalExpand = true });
            var cb = new Button { Text = "Claim", MinWidth = 60 };
            var oid = o.OrderId;
            cb.OnPressed += _ => OnClaim?.Invoke(oid);
            row.AddChild(cb);
            MyCompletedContainer.AddChild(row);
        }
    }

    public void UpdateFeed(List<MarketFeedEntry> feed)
    {
        FeedContainer.RemoveAllChildren();
        if (feed.Count == 0) { FeedContainer.AddChild(new Label { Text = "No market activity yet.", StyleClasses = { "LabelSubText" }, Margin = new Thickness(4) }); return; }
        foreach (var e in feed)
            FeedContainer.AddChild(new Label { Text = $"[{e.Time.ToLocalTime():HH:mm}] {e.Text}", StyleClasses = { "LabelSubText" } });
    }

    private void UpdateFeeLabel()
    {
        var cur = (string?)OrderCurrencyBtn.SelectedMetadata;
        if (string.IsNullOrEmpty(cur) || !int.TryParse(OrderPrice.Text, out var p) || p <= 0) { OrderFeeLabel.Text = ""; return; }
        if (cur == "Barter") { OrderFeeLabel.Text = "No fee"; return; }
        OrderFeeLabel.Text = $"Fee: {p / 10} {cur}";
    }

    public void OnSearchResults(List<(string Id, string Name)> results)
    {
        ProtoResultsContainer.RemoveAllChildren();
        foreach (var (id, name) in results)
        {
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 8 };
            row.AddChild(new Label { Text = $"{name} ({id})", HorizontalExpand = true, VerticalAlignment = VAlignment.Center });
            var sel = new Button { Text = "Select", MinWidth = 50 };
            sel.OnPressed += _ =>
            {
                _selectedProtoId = id;
                _selectedProtoName = name;
                SelectedProtoLabel.Text = $"{name} ({id})";
            };
            row.AddChild(sel);
            ProtoResultsContainer.AddChild(row);
        }
    }

    private void SubmitOrder()
    {
        var isBuy = (bool?)OrderTypeBtn.SelectedMetadata ?? false;
        var cur = (string?)OrderCurrencyBtn.SelectedMetadata ?? "Bottlecaps";
        if (!int.TryParse(OrderPrice.Text, out var price) || price <= 0) return;
        if (!int.TryParse(OrderQty.Text, out var qty) || qty <= 0) qty = 1;
        if (_selectedProtoId == null) return;
        OnListRequest?.Invoke(new CreateOrderMessage(_selectedProtoId, qty, cur, price, isBuy));
    }
}
