using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.Medical.Cryogenics;


[GenerateTypedNameReferences]
public sealed partial class MisfitsCryoMetricControl : PanelContainer
{
    private readonly StyleBoxFlat _progressStyle = new();

    public MisfitsCryoMetricControl()
    {
        RobustXamlLoader.Load(this);
        Progress.ForegroundStyleBoxOverride = _progressStyle;
        SetAccentColor(Color.White);
    }

    public void SetAccentColor(Color color)
    {
        Accent.PanelOverride = new StyleBoxFlat { BackgroundColor = color };
        _progressStyle.BackgroundColor = color;
    }

    public void Update(string title, string value, string? target = null, float? progress = null)
    {
        Title.Text = title;
        Value.Text = value;
        Target.Text = target;
        Target.Visible = target != null;

        Progress.Visible = progress != null;
        if (progress != null)
            Progress.Value = Math.Clamp(progress.Value, 0f, 1f);
    }
}
