using Content.Client.UserInterface.Controls;
using Content.Shared._Misfits.Medical.Cryogenics;
using Content.Shared.FixedPoint;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._Misfits.Medical.Cryogenics;

[GenerateTypedNameReferences]
public sealed partial class MisfitsCryoPodWindow : FancyWindow
{
    public MisfitsCryoPodWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(MisfitsCryoPodBoundUserInterfaceState state)
    {
        PatientLabel.Text = $"Patient: {state.PatientName}" + (state.PatientCritical ? " (CRITICAL)" : "");
        TemperatureLabel.Text = $"Temperature: {state.PatientTemperature:F0}K (target {state.TargetTemperature:F0}K)";
        TemperatureLabel.FontColorOverride = state.PatientTemperature <= state.TargetTemperature + 5f
            ? new Color(0.55f, 0.75f, 1f)
            : Color.White;

        GraphStateLabel.Text = state.GraphState switch
        {
            MisfitsCryoGraphState.Reacting => "Chamber is reacting - stasis and catalyst are cooking into slurry!",
            MisfitsCryoGraphState.Catalyzing => "Catalyzing - stabilizer is holding the reaction steady.",
            _ => "Safe - stasis and catalyst are not converging.",
        };
        GraphStateLabel.FontColorOverride = state.GraphState switch
        {
            MisfitsCryoGraphState.Reacting => new Color(0.85f, 0.35f, 0.35f),
            MisfitsCryoGraphState.Catalyzing => new Color(0.35f, 0.85f, 0.45f),
            _ => Color.White,
        };

        ReagentList.RemoveAllChildren();
        foreach (var reagent in state.Reagents)
        {
            ReagentList.AddChild(BuildReagentRow(reagent));
        }

        var maxVol = (float) state.ChamberMaxVolume.Float();
        SlurryBar.SetReading((float) state.SlurryQuantity.Float(), maxVol, state.SlurryQuantity <= FixedPoint2.New(2));
        SlurryTitleLabel.Text = $"Necrotic byproduct: {state.SlurryQuantity}u";
    }

    private static Control BuildReagentRow(MisfitsCryoReagentReadout reagent)
    {
        var container = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(0, 2, 0, 4),
        };

        var header = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
        header.AddChild(new Label
        {
            Text = reagent.Name,
            HorizontalExpand = true,
            FontColorOverride = reagent.Color,
        });
        header.AddChild(new Label
        {
            Text = $"{reagent.Quantity}u (target {reagent.TargetMin}-{reagent.TargetMax}u)",
        });
        container.AddChild(header);

        var inBand = reagent.Quantity >= reagent.TargetMin && reagent.Quantity <= reagent.TargetMax;
        var bar = new MisfitsCryoMeterBar { MinHeight = 16 };
        bar.SetReading((float) reagent.Quantity.Float(), 50f, inBand);
        container.AddChild(bar);

        return container;
    }
}
